version: "3.8"
services:
  genres_service:
    container_name: genres_service
    image: genres_service_template
    restart: always
    build:
      context: ./genres
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - API_URL=http://localhost
      - API_PORT=3000
      - DB_MONGO_URL=mongodb://mongo:27017    #this string is different form .env file
    depends_on:
      - mongo
    networks:
      - node-network
  movie_service:
    container_name: movie_service
    image: movie_service_template
    restart: always
    build:
      context: ./movie
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - API_URL=http://localhost
      - API_PORT=3001
      - DB_MONGO_URL=mongodb://mongo:27017    #this string is different form .env file
    depends_on:
      - mongo
    networks:
      - node-network
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: challenge_db
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./db-data/:/data/db
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
